// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAEDvC9iJP8UdFecKUsHCr_-UQ2WbcPos',
    appId: '1:528501920360:web:658571662da0468e56e1dd',
    messagingSenderId: '528501920360',
    projectId: 'caretracker-7124d',
    authDomain: 'caretracker-7124d.firebaseapp.com',
    storageBucket: 'caretracker-7124d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0c1vGCGGawQYxGIx6B4Xj_gZYND6OdVg',
    appId: '1:528501920360:android:a06cafd6d311024f56e1dd',
    messagingSenderId: '528501920360',
    projectId: 'caretracker-7124d',
    storageBucket: 'caretracker-7124d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdo4_M_6GXZiwZjxJIckDaVEDG2exoW4Q',
    appId: '1:528501920360:ios:4ef6c31d0283fe5556e1dd',
    messagingSenderId: '528501920360',
    projectId: 'caretracker-7124d',
    storageBucket: 'caretracker-7124d.appspot.com',
    iosClientId:
        '528501920360-f8ff85oen7a2ehlmg5pbllrl46shkb1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.careTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdo4_M_6GXZiwZjxJIckDaVEDG2exoW4Q',
    appId: '1:528501920360:ios:4ef6c31d0283fe5556e1dd',
    messagingSenderId: '528501920360',
    projectId: 'caretracker-7124d',
    storageBucket: 'caretracker-7124d.appspot.com',
    iosClientId:
        '528501920360-f8ff85oen7a2ehlmg5pbllrl46shkb1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.careTracker',
  );
}
